apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-simulator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ton-utilisateur/solar-monitoring-gitops'
    targetRevision: main
    path: k8s/apps/solar-simulator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: solar-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
