apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: solar-simulator
  labels:
    app: solar-simulator
    release: prometheus
spec:
  selector:
    matchLabels:
      app: solar-simulator
  endpoints:
    - port: metrics
      interval: 30s
