apiVersion: v1
kind: Service
metadata:
  name: solar-simulator
  namespace: solar-prod
spec:
  selector:
    app: solar-simulator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
